### ISSUE TITLE
Permissions issue in jenkins/slave:latest

### ISSUE THREAD

**Issue by doubliez** [jenkinsci/docker-agent#45] opened 2018-12-28 01:21 UTC
I was using `jenkins/slave` (i.e. `latest` tag) as remoting image for Docker Slaves plugin, and it stopped working recently with the following error:

```
Exception in thread "main" java.io.IOException: Failed to initialize the default JAR Cache location
	at hudson.remoting.JarCache.getDefault(JarCache.java:41)
	at hudson.remoting.ChannelBuilder.withJarCacheOrDefault(ChannelBuilder.java:220)
	at hudson.remoting.Launcher.main(Launcher.java:736)
	at hudson.remoting.Launcher.runWithStdinStdout(Launcher.java:691)
	at hudson.remoting.Launcher.run(Launcher.java:373)
	at hudson.remoting.Launcher.main(Launcher.java:283)
Caused by: java.lang.IllegalArgumentException: Root directory not writable: ?/.jenkins/cache/jars
	at hudson.remoting.FileSystemJarCache.<init>(FileSystemJarCache.java:62)
	at hudson.remoting.JarCache.getDefault(JarCache.java:39)
	... 5 more
Caused by: java.nio.file.AccessDeniedException: /home/jenkins/?
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at hudson.remoting.Util.mkdirs(Util.java:231)
	at hudson.remoting.FileSystemJarCache.<init>(FileSystemJarCache.java:60)
	... 6 more
```

I saw this recent commit which I suspect to be the cause: https://github.com/jenkinsci/docker-slave/commit/723d12eea77b5d5bc3082612c12e30e422e237f2

Using `jenkins/slave:3.27-1` instead of `latest` tag fixed the issue.

**Comment by oleg-nenashev** [comment] 2018-12-28 05:02
@doubliez Could you please create a bug to the `remoting` component in https://issues.jenkins-ci.org ? Looks like a regression in Remoting, CC @jeffret-b

**Comment by doubliez** [comment] 2018-12-28 19:04
Ok, I did that now: https://issues.jenkins-ci.org/browse/JENKINS-55354

@jeffret-b I didn't see a WARNING log message associated with the exception. I put a little more of the console output in the ticket, but it doesn't tell much more.

**Comment by slide** [comment] 2020-04-28 22:27
Closing since there is tracking in Jira.

**Closed by slide** 2020-04-28 22:27 UTC
