### ISSUE TITLE
Current `latest-bullseye-jdk11` is a `bookworm`

### ISSUE THREAD

**Issue by dhs-rec** [jenkinsci/docker-agent#515] opened 2023-10-10 05:38 UTC
### Jenkins and plugins versions report

Hi,

the current `jenkins/agent:latest-bullseye-jdk11` is not `bullseye`, but `bookworm`:
```
% docker run -it jenkins/agent:latest-bullseye-jdk11 cat /etc/debian_version
12.1
```
Please fix.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Not relevant

### Reproduction steps

See description

### Expected Results

Get a `bullseye` container.

### Actual Results

Got a `bookworm` container.

**Comment by dduportal** [comment] 2023-10-10 21:30
I'm reopening as it was closed by #516 automatically : until we have released a new version, the issue still stands.

**Comment by MarkEWaite** [comment] 2023-10-10 23:56
> I'm reopening as it was closed by #516 automatically : until we have released a new version, the issue still stands.

If we want to create a new container version that is bullseye based, won't we need to add bullseye back to the container images at least long enough to generate a new release?  Currently, there are no bullseye tags defined in the file and no mention of bullseye in the container definitions.  If we need to deliver a "terminal version" of `bullseye-jdk11`, I think that we'll need to bring back those container definitions long enough to create them at least once, then we can remove them again.

**Comment by dduportal** [comment] 2023-10-11 06:26
> > I'm reopening as it was closed by #516 automatically : until we have released a new version, the issue still stands.
> 
> If we want to create a new container version that is bullseye based, won't we need to add bullseye back to the container images at least long enough to generate a new release? Currently, there are no bullseye tags defined in the file and no mention of bullseye in the container definitions. If we need to deliver a "terminal version" of `bullseye-jdk11`, I think that we'll need to bring back those container definitions long enough to create them at least once, then we can remove them again.

oh true that, I was thinking `latest` tag but it is not the case. With https://github.com/jenkinsci/docker-agent/pull/517 it is now clearer.

Closing, thanks!

**Comment by timja** [comment] 2023-10-12 08:03
No I don't think it has been fixed.

**Comment by lemeurherve** [comment] 2023-10-12 08:05
Should a `bullseye` version be added back in complement of the `bookworm` one?

**Comment by dhs-rec** [comment] 2023-10-12 08:06
Yes, please.

**Comment by timja** [comment] 2023-10-12 08:07
> Should a `bullseye` version be added back in complement to the `bookworm` one?

yes but just a terminal one to fix the tag and then removed after.

**Comment by dhs-rec** [comment] 2023-10-12 08:12
The reason we can't update to the bookworm image yet is that its `default-jre` is Java 17, but it can't be installed a.t.m.:
```
#9 8.588 update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/java to provide /usr/bin/java (java) in auto mode
 #9 8.589 update-alternatives: error: error creating symbolic link '/usr/share/man/man1/java.1.gz.dpkg-tmp': No such file or directory
 #9 8.589 dpkg: error processing package openjdk-17-jre-headless:amd64 (--configure):
 #9 8.589  installed openjdk-17-jre-headless:amd64 package post-installation script subprocess returned error exit status 2
```
(Guess this needs another issue?)

**Comment by gounthar** [comment] 2023-10-12 08:46
I can confirm I am facing the same issue:

```bash
dpkg: error processing package default-jre (--configure):
 dependency problems - leaving unconfigured
Processing triggers for fontconfig (2.14.1-4) ...
Processing triggers for libc-bin (2.36-9+deb12u1) ...
Processing triggers for libgdk-pixbuf-2.0-0:amd64 (2.42.10+dfsg-1+b1) ...
Errors were encountered while processing:
 openjdk-17-jre-headless:amd64
 openjdk-17-jre:amd64
 default-jre
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Why install 'default-jre' (which is JDK 17) on a 'jdk11' image? Wouldn't it be more suitable to use our 'jdk17' image for this purpose?

```bash
docker container run -it -u root jenkins/agent:latest-bullseye-jdk17 bash
root@b2f156cb5124:/home/jenkins# java -version
openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (build 17.0.8.1+1, mixed mode)
root@b2f156cb5124:/home/jenkins#
```

I'm sorry if I misunderstood your specific use case. I don't believe the current limitation is related to the Jenkins Docker agent. It might be a good idea to open an issue directly in the Debian repository.

**Comment by timja** [comment] 2023-10-12 08:58
> The reason we can't update to the bookworm image yet is that its `default-jre` is Java 17, but it can't be installed a.t.m.:
> 
> ```
> #9 8.588 update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/java to provide /usr/bin/java (java) in auto mode
>  #9 8.589 update-alternatives: error: error creating symbolic link '/usr/share/man/man1/java.1.gz.dpkg-tmp': No such file or directory
>  #9 8.589 dpkg: error processing package openjdk-17-jre-headless:amd64 (--configure):
>  #9 8.589  installed openjdk-17-jre-headless:amd64 package post-installation script subprocess returned error exit status 2
> ```
> 
> (Guess this needs another issue?)

You can install a Java installation from a different provider or just download the tarball and extract it.

**Comment by lemeurherve** [comment] 2023-10-12 09:01
> Why install '`default-jre`' (which is JDK 17) on a '`jdk11`' image? Wouldn't it be more suitable to use our '`jdk17`' image for this purpose?
> 
> ```shell
> docker container run -it -u root jenkins/agent:latest-bullseye-jdk17 bash
> root@b2f156cb5124:/home/jenkins# java -version
> openjdk version "17.0.8.1" 2023-08-24
> OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)
> OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (build 17.0.8.1+1, mixed mode)
> root@b2f156cb5124:/home/jenkins#
> ```

`latest` is bad 😛 Especially since the image you're proposing also suffers from the same issue as the latest-bullseye-jdk11 😅 

```
$ docker run -it jenkins/agent:latest-bullseye-jdk17 cat /etc/debian_version
12.1
```

Use a versioned image instead ([3148.v532a_7e715ee3-5](https://github.com/jenkinsci/docker-agent/releases/tag/3148.v532a_7e715ee3-5) is the last version before the switch to `bookworm` if you really want to stay on `bullseye`):

```
$ docker run -it jenkins/agent:3148.v532a_7e715ee3-5-jdk17 cat /etc/debian_version
11.7
$ docker run -it jenkins/agent:3148.v532a_7e715ee3-5-jdk17 java -version          
openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (build 17.0.8.1+1, mixed mode)
```

**Comment by lemeurherve** [comment] 2023-10-12 09:08
In that case I'd suggest using `jenkins/agent:3148.v532a_7e715ee3-5-jdk11`:

```
$ docker run -it jenkins/agent:3148.v532a_7e715ee3-5-jdk11 cat /etc/debian_version
11.7

$ docker run -it jenkins/agent:3148.v532a_7e715ee3-5-jdk11 java -version          
openjdk version "11.0.20.1" 2023-08-24
OpenJDK Runtime Environment Temurin-11.0.20.1+1 (build 11.0.20.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.20.1+1 (build 11.0.20.1+1, mixed mode)
```

**Comment by dhs-rec** [comment] 2023-10-12 09:09
> You can install a Java installation from a different provider or just download the tarball and extract it.

That's a workaround, not a fix. I don't like workarounds ;-) Anyway, see my previous comment above.

**Comment by timja** [comment] 2023-10-12 09:38
You shouldn't be installing that package as it changes the JDK.

This should be handled in this image really but the simplest workaround for now is to run this:
https://github.com/adoptium/containers/blob/7360285847f9a281dfb23682be1351482a5ebe58/17/jdk/alpine/entrypoint.sh#L25-L27

**Comment by dhs-rec** [comment] 2023-10-12 09:39
> I'm sorry if I misunderstood your specific use case. I don't believe the current limitation is related to the Jenkins Docker agent. It might be a good idea to open an issue directly in the Debian repository.

From your `java -version` outputs above I see that the installed Java is a Temurin one, not the one from Debian...

**Comment by lemeurherve** [comment] 2023-10-12 10:12
> > I'm sorry if I misunderstood your specific use case. I don't believe the current limitation is related to the Jenkins Docker agent. It might be a good idea to open an issue directly in the Debian repository.
> 
> From your `java -version` outputs above I see that the installed Java is a Temurin one, not the one from Debian...

Not sure to understand, this is one of the goal of this repo image, using Temurin as base for Java and its JDK. Did I miss something?

**Comment by dhs-rec** [comment] 2023-10-12 10:19
This was reg. "open an issue directly in the Debian repository". If it's not from Debian, why open an issue there?

**Comment by gounthar** [comment] 2023-10-12 12:27
I apologize if my previous message wasn't clear.
In my view, the issue with installing `ca-certificates` on top of the Jenkins image seems to be more related to Debian than Jenkins.
That's why I recommended filing an issue directly with Debian.

Regarding `ca-certificates`, I was able to install it using this command: `apt install ca-certificates --no-install-recommends`.

**Comment by lemeurherve** [comment] 2023-10-12 12:48
> > Should a `bullseye` version be added back in complement to the `bookworm` one?
> 
> yes but just a terminal one to fix the tag and then removed after.

Opened https://github.com/jenkinsci/docker-agent/pull/522

Should I include jdk17 too or should I keep only jdk11 in this last set of images?

**Comment by dhs-rec** [comment] 2023-10-12 13:41
BTW: The error is a direct result of removing `/usr/share/man/*` from the image (see `Debian/Dockerfile`, line 82).

**Comment by lemeurherve** [comment] 2023-10-12 13:46
Please open a distinct issue for that.

**Comment by lemeurherve** [comment] 2023-10-12 14:14
> Should I include jdk17 too or should I keep only jdk11 in this last set of images?

jdk17 images added in the PR.

**Closed** 2023-10-12 14:39 UTC
Labels: bug

**Comment by lemeurherve** [comment] 2023-10-12 15:42
To finish on this issue, new **and last** `bullseye` images published for jdk11 & jdk17: https://github.com/jenkinsci/docker-agent/releases/tag/3148.v532a_7e715ee3-13

```
$ docker run -it jenkins/agent:latest-bullseye-jdk11 cat /etc/debian_version
Digest: sha256:19f6937eabb0aef20405377aaeb60c52ffd81fc68bc7519b9db8b277d14538b5
11.7

$ docker run -it jenkins/agent:latest-bullseye-jdk17 cat /etc/debian_version
Digest: sha256:a360da4137ec7deca2278afd931eafb5a3b1e99a93892df0262f17c4f16406bb
11.7

$ docker run -it jenkins/agent:bullseye-jdk11 cat /etc/debian_version
Digest: sha256:19f6937eabb0aef20405377aaeb60c52ffd81fc68bc7519b9db8b277d14538b5
11.7

$ docker run -it jenkins/agent:bullseye-jdk17 cat /etc/debian_version
Digest: sha256:a360da4137ec7deca2278afd931eafb5a3b1e99a93892df0262f17c4f16406bb
11.7
```
