### ISSUE TITLE
Require image for ARM64 architecture 

### ISSUE THREAD

**Issue by odidev** [jenkinsci/docker-agent#180] opened 2021-07-13 08:07 UTC
Hi Team, 

I am trying to use **jenkins/jnlp-slave** image on ARM64 architecture but it seems the arm64 supported tag is not available in the docker hub. 

I have tried building the image on the arm64 platform using **docker build -t image_name -f 11/debian/Dockerfile .** command, but it is failing as base image **jenkins/agent** is not available for the arm64 platform.
  
I have successfully built the base image using the command **docker build -t image_name .** on the arm64 platform by making some changes in the Dockerfile and using the manually build base image jenkins/agent, I am able to build jenkins/jnlp-slave successfully.
 
I have used **GitHub action** to build and push the **jenkins/agent** image for both the platforms. 

**Commit Link -** https://github.com/odidev/docker-agent/commit/138e52328cd8c7af305614279a3e3b1f0a866f03
 
**GitHub action link -** https://github.com/odidev/docker-agent/runs/3054193105?check_suite_focus=true
 
**Docker Hub Link -** https://hub.docker.com/repository/registry-1.docker.io/odidev/docker-agent/tags?page=1&ordering=last_updated
 
Do you have any plans on releasing arm64 images? 

It will be very helpful if an arm64 image is available. If interested, I will raise a PR.

**Comment by MarkEWaite** [comment] 2021-07-13 13:57
Yes, we're very interested in Arm support for the controller and the agents.  We have a [work in progress adding `docker bake` support for controller images](https://github.com/jenkinsci/docker/issues/1139) that use Arm, PPC64, and s390x.  If you'd like to assist with that work, that would help orient you towards the techniques that will likely then be used to add similar support to the agent images.

Arm support in the Docker images is on the [Jenkins roadmap](https://www.jenkins.io/project/roadmap/) as well.  More details are available in the [GitHub issue](https://github.com/jenkinsci/docker/issues/1139) and the [Jira issue](https://issues.jenkins.io/browse/JENKINS-61775)

**Comment by timja** [comment] 2021-07-30 13:27
Duplicate of https://github.com/jenkinsci/docker-agent/issues/109

**Closed by timja** 2021-07-30 13:27 UTC

**Comment by timja** [comment] 2021-07-30 13:28
> It will be very helpful if an arm64 image is available. If interested, I will raise a PR.

Please do, we will be doing this via QEMU emulation with `docker buildx bake` the same as in https://github.com/jenkinsci/docker

The scripts need to be updated to that first and then enabled for multi-arch after
